name: CI/CD Workflow

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Set environment variable from secret
      - name: Set Environment Variable
        env:
          FIREBASE_SECRET: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: echo "FIREBASE_SECRET=$FIREBASE_SECRET" >> $GITHUB_ENV

      # Here, you can add the rest of your build and deployment steps
      # ...


